ls-fontes/repositorio_teste

index.html
=> teste robson

index.html
=> teste de comit no meu braço

index.html
=> gabrielfioriteste

Arquivo Arthur Fonsatti.html
/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
=> Criado arquivo para Arthur Fonsatti

amesaredonda.html
=> A Mesa Redonda

mesa_Azul.html
Reverts ls-fontes/repositorio_teste#91
=> "Atualização mesa_Azul.html"

cristhian.html
=> Adicionado arquivo html

viniciusmenarim.html
=> Adicionando frase

index.html, professor.html
=> Concluído solicitação #148

Imagem-cachorro-153.html
=> Adicionando imagem dog

agrandemesa.html
=> Concluído solicitação #158

victorminamihara.html
=> Concluído Tarefa#154

quadrimesa.html
=> Concluído solicitação #171

gabrielfiori.html
=> Adicionando imagem #191

viniciusmenarim.html
=> Adicionar imagem

joaogabriel.html
=> #157-Vírus removido

gustavoomodei.html
=> Adicionado receita

gabrielfiori.html
=> Adicionando imagem #200

cristhian.html
=> Concluído solicitação #177

amesaredonda.html
=> #213 Escreva Hello World

viniciusportes.html
=> #202 Adicionar imagem meu arquivo

#201-video.html
=> concluido solicitção #201

julianoferreira.html
=> pedido fechado

gabrielfiori.html
=> Mudando a cor da minha página

mesadocapacete.html
=> Adicionando oi na mesadocapacete

cristhian.html
=> #261 oi biel

victorminamihara.html
=> Concluído POEMA #253

viniciusportes.html
=> #250-Mudar-Cor-Vinicius

victorminamihara.html
=> Concluído GIF#272

IgorMoro.html
=> Concluído solicitação #276

cristhian.html
=> #275 adicionado link

#190-lucasTeste.html, #263-lucasMusica.html
feito na issue adição de musica pedido por chistian
=> #263-lucasMusica

amesaredonda.html
=> #277 CantadaRuim

#298-musica.html
=> concluido slicitação

IgorMoro.html
=> Concluído solicitação #262

#282-LucasFrase.html
=> commit criado
